config/routes.rb
Community::Application.routes.draw do
  devise_for :members,:controllers => { :registrations =>'registration'}
  devise_for :members ,:controllers => {:passwords => "passwords"} do
    resources :passwords
  end

  match 'dashboard' => 'home#dashboard'

  match 'register' =>'registration#register'
  
  root :to => 'home#index'

  resources :contacts
  resources :accounts
  resources :contracts
  resources :opportunity
  resources :users
  resources :roles

  resources :leads do
    collection do
      put :convert_lead
    end
  end
  match 'lead/:id/convert' => 'leads#convert_lead', :as => :convert_lead
  match 'leads/:id' => 'leads#update', :via => [:post]
  match 'contacts/:id' => 'contacts#update', :via => [:post]
  match 'accounts/:id' => 'accounts#update', :via => [:post]
  match 'account/:id/get_contacts' => 'accounts#get_contacts', :as => :get_contacts, :via => [:get]
  match 'users/:id/edit' => 'users#update', :via => [:post]
  match 'passwords/:id/edit' => 'passwords#update', :via => [:post]
  match 'users/new' => 'users#create', :via => [:post]
  match 'roles/:id/edit' => 'roles#update', :via => [:post]
  match 'roles/new' => 'roles#create', :via => [:post]

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  belongs_to :member, :foreign_key => "owner"
  # Mass Assignment Protection
  attr_accessible :firstname, :lastname, :title, :company, :status, :phone, :email, :ratting,
                  :website, :street, :city, :state, :zip, :country, :annual_revenue, :employee_no,
                  :lead_source, :description, :owner, :unique_id

  # Validations for Users
  validates_presence_of :lastname, :company, :status, :email
  validates_format_of  :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :email

  def self.search_leads(search_leads, sort_column, sort_direction)
    Lead.where('lastname LIKE  ?', "%#{search_leads}%").order(sort_column+ " "+sort_direction)
  end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_filter :authenticate_user

  def new
    @lead = Lead.new
  end

  def index
    @leads = Lead.find(:all, :conditions => [ "status = ?", "Open" ])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @lead = Lead.new(params[:lead])
    @lead[:owner] =  current_member.id
    @lead[:unique_id] = genarate_unique_key
    respond_to do |format|
      begin
        if @lead.save
          format.json { render :json => {"success" => true, "message" => "Successfully created!"} }
        else
          format.json { render :json => {"error" => true, "exception" => @lead.errors.full_messages.to_sentence} }
        end
      rescue =>e
        @error= e.message
        format.json { render :json => {"error" => true, "exception" => @error} }
      end
    end
  end

  def show
    @title = t "lead.t_view"
    @lead = Lead.find_by_unique_id(params[:id])
  end

  def edit
    @title = t "lead.t_edit_lead"
    @lead = Lead.find_by_unique_id(params[:id])
  end

  def update
    @title = t "user.t_update_lead"
    @lead = Lead.find_by_unique_id(params[:id])
    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        flash[:notice] = "Successfully updated the lead!"
        format.html { redirect_to(:action => "show") }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @lead.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @title = t "user.t_delete_lead"
    @lead = Lead.find_by_unique_id(params[:id])
    @lead.destroy
    respond_to do |format|
      flash[:notice] = "lead deleted successfully!"
      format.html { redirect_to(leads_path) }
    end
  end

  def convert_lead
    begin
      @lead = Lead.find_by_unique_id(params[:id])
      @find = Account.where("account_name = ?", @lead.company)
      if @find.empty?
        @account = Account.new
        @account.account_name = @lead.company
        @account.status = 1
        @account.phone = @lead.phone
        @account.website = @lead.website
        @account.annual_revenue = @lead.annual_revenue
        @account.employees = @lead.employee_no
        @account.description = @lead.description
        @account.b_street = @lead.street
        @account.b_city = @lead.city
        @account.b_state = @lead.state
        @account.b_zip = @lead.zip
        @account.b_country = @lead.country
        @account.owner = @lead.owner
        @account.unique_id = genarate_unique_key
        if @account.save
          @accountId = @account.id
        else
          flash[:error] = @account.errors.full_messages.to_sentence
        end
      else
        @find = Account.where("account_name = ?", @lead.company).first
        @accountId = @find.id
      end
      @contact = Contact.new
      @contact.firstname = @lead.firstname
      @contact.lastname = @lead.lastname
      @contact.title = @lead.title
      @contact.status = 1
      @contact.account_name = @accountId
      @contact.phone = @lead.phone
      @contact.email = @lead.email
      @contact.m_street = @lead.street
      @contact.m_city = @lead.city
      @contact.m_state = @lead.state
      @contact.m_zip = @lead.zip
      @contact.m_country = @lead.country
      @contact.owner = @lead.owner
      @contact.unique_id = genarate_unique_key

      if @contact.save
        @lead.update_attribute(:status, "Qualified")
        flash[:notice] = "Lead converted successfully!"
      else
        flash[:error] = @contact.errors.full_messages.to_sentence
      end
      respond_to do |format|
        format.html { redirect_to(leads_path) }
      end
    rescue =>e
      respond_to do |format|
        flash[:error] = e.message
        format.html { redirect_to(leads_path) }
      end
    end
  end

end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/_lead_list.html.erb
<div class="row-fluid">
  <div class="span12">
    <%if @leads.count <= 0 %>
      <div class="alert alert-notice">There is no leads found!</div>
    <%  else %>
      <table class="table table-bordered table-hover table table-condensed">
        <thead>
          <tr>
            <th><%= (t "lead.title") %></th>
            <th><%= (t "lead.first_name") %></th>
            <th><%= (t "lead.last_name") %></th>
            <th><%= (t "lead.company") %></th>
            <th><%= (t "lead.email") %></th>
            <th><%= (t "lead.phone") %></th>
            <th colspan="2"><%= (t "lead.status") %></th>
          </tr>
        </thead>
        <tbody>
          <% for lead in @leads do %>
              <tr class="<%= cycle :odd, :even %>">
                <td style="text-transform:capitalize;">
                  <% if lead.title.nil? || lead.title == '' %>
                    N/A
                  <% else %>
                    <%= lead.title %>
                  <% end %>
                </td>
                <td>
                  <% if lead.firstname.nil? || lead.firstname == '' %>
                    N/A
                  <% else %>
                    <%= lead.firstname %>
                  <% end %>
                </td>
                <td><%= lead.lastname %></td>
                <td>
                  <% if lead.company.nil? || lead.company == '' %>
                    N/A
                  <% else %>
                    <%= lead.company %>
                  <% end %>
                </td>
                <td><%= lead.email %></td>
                <td>
                  <% if lead.phone.nil? || lead.phone == '' %>
                    N/A
                  <% else %>
                    <%= lead.phone %>
                  <% end %>
                </td>
                <td style="text-transform:capitalize;"><%= lead.status %></td>
                <td>
                  <div class="btn-group">
                    <a class="btn btn-small" href="<%= lead_path(:id => lead.unique_id) %>">Details</a>
                    <a class="btn btn-small" href="<%= edit_lead_path(:id => lead.unique_id) %>">Edit</a>
                    <a class="btn btn-small" href="<%= convert_lead_path(:id => lead.unique_id) %>">Convert Lead</a>
                    <%= link_to "Delete", lead_path(:id => lead.unique_id),:confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <%  end %>
    </div>
  </div>

app/views/leads/edit.html.erb
<div class="row-fluid page-title">
  <h2>Update Lead</h2>
</div>
<div id="editLead">
  <div id="ajaxHandler">
    <div class="row-fluid">
      <div id="crmAjaxProgress" class="progress progress-striped active" style="display: none;">
        <div class="bar" style="width: 100%;"></div>
      </div>
      <div id="crmAjaxMessage" class="alert" style="display: none;">
        Error!
      </div>
    </div>
  </div>
  <%= simple_form_for(@lead, :url => lead_path(:id => @lead.unique_id), :method => :update, :html => {:class => "form-horizontal"})  do |f| %>
    <div class="field-set-container">
      <h1 class="title">Personal Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :title, :collection =>[["Mr.","Mr."],["Mrs.","Mrs."]], :selected => @lead.title %>
            <%= f.input :firstname, :label => (t "lead.firstname") %>
            <%= f.input :lastname, :label =>(t "lead.lastname") %>
            <%= f.input :email, :label =>(t "lead.email") %>
          </div>
          <div class="span5">
            <%= f.input :status, :collection =>[["Contacted","Contacted"],["Open","Open"],["Qualified","Qualified"],["Unqualified","Unqualified"]], :selected => @lead.status %>
            <%= f.input :company, :label =>(t "lead.company") %>
            <%= f.input :phone, :label =>(t "lead.phone") %>
            <%= f.input :ratting, :collection =>[["Select",""],["Hot","Hot"],["Warm","Warm"],["Cold","Cold"]], :selected => @lead.ratting %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Address Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :street, :as => :text, :input_html => { :cols => 50, :rows => 3 } %>
          </div>
          <div class="span5">
            <%= f.input :city, :label =>(t "lead.city") %>
            <%= f.input :state, :label =>(t "lead.state") %>
            <%= f.input :zip, :label =>(t "lead.zip") %>
          </div>
        </div>
      </div>
    </div>
    <div class="field-set-container">
      <h1 class="title">Other Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :annual_revenue, :label =>(t "lead.annual_revenue") %>
            <%= f.input :employee_no, :label =>(t "lead.no_of_employee") %>
            <%= f.input :lead_source, :label =>(t "lead.lead_source") %>
          </div>
          <div class="span5">
            <%= f.input :description, :as => :text, :input_html => { :cols => 50, :rows => 3 } %>
          </div>
        </div>
      </div>
    </div>


    <div class="form-actions">
      <div class="btn-group">
        <%= f.submit nil, :class => "btn btn-primary" %>
          <a class="btn btn-small" href="<%= lead_path(:id => @lead.unique_id) %>">Cancel</a>
      </div>
    </div>
  <% end %>
</div>

app/views/leads/index.html.erb
<div class="row-fluid page-title">
  <h2>Leads <span class="aside-title-link">[<%= link_to "create", new_lead_path %>]</span></h2>
</div>

<%= render :partial => 'leads/lead_list' %>

app/views/leads/new.html.erb
<script>
  form = '', widget = '';
  $.fn.doCreateLead = function(){
    form = $(this);
    widget = $('#createLead');
    $(".alert, .progress, #new_lead", widget).hide();
    $(".progress", widget).show();
    $.post('../leads', form.serialize(), function(data){
      $(".alert, .progress", widget).hide();
      if(data.success){
        $(".alert", widget)
        .removeClass('alert-error')
        .addClass('alert-success')
        .html(data.message)
        .show();
        setTimeout("window.location.href = '/leads'",1000);
      } else {
        var $ul = $('<ul/>');
        $ul.addClass('error');
        if (data.exception.indexOf('{') == 0) {
          e = jQuery.parseJSON(data.exception);
          jQuery.each(e, function(key, value) {
            $ul.append('<li>' + value.toString() + '</li>');
          });
        } else {
          $ul.append('<li>' + data.exception + '</li>');
        }
        $(".progress", widget).hide();
        $(".alert", widget)
        .removeClass('alert-success')
        .addClass('alert-error')
        .html($ul)
        .show();
        $("#new_lead", widget).show();
      }

    }).fail(function() {
      $(".progress", widget).hide();
      $(".alert", widget)
      .removeClass('alert-success')
      .addClass('alert-error')
      .html("Error while processing the request!")
      .show();
      $("#new_lead", widget).show();
    });
  }



  $(document).ready(function(){
    $("#new_lead").validate({
      submitHandler: function(form) {
        $(form).doCreateLead();
        return false;
      }
    });
  });

</script>

<div class="row-fluid page-title">
  <h2>Create Lead</h2>
</div>
<div id="createLead">
  <div id="ajaxHandler">
    <div class="row-fluid">
      <div id="crmAjaxProgress" class="progress progress-striped active" style="display: none;">
        <div class="bar" style="width: 100%;"></div>
      </div>
      <div id="crmAjaxMessage" class="alert" style="display: none;">
        Error!
      </div>
    </div>
  </div>
  <%= simple_form_for @lead, :remote=>true, :html => { :class => "form-horizontal", :onsubmit => "return false;"}  do |f| %>
    <div class="field-set-container">
      <h1 class="title">Personal Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :title, :collection =>[["Mr.","Mr."],["Mrs.","Mrs."]], :selected => "Mr." %>
            <%= f.input :firstname, :label => (t "lead.firstname") %>
            <%= f.input :lastname, :label =>(t "lead.lastname") %>
            <%= f.input :email, :label =>(t "lead.email") %>
          </div>
          <div class="span5">
            <%= f.input :status, :collection =>[["Contacted","Contacted"],["Open","Open"],["Qualified","Qualified"],["Unqualified","Unqualified"]], :selected => "Open" %>
            <%= f.input :company, :label =>(t "lead.company") %>
            <%= f.input :phone, :label =>(t "lead.phone") %>
            <%= f.input :ratting, :collection =>[["Select",""],["Hot","Hot"],["Warm","Warm"],["Cold","Cold"]], :selected => "" %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Address Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :street, :as => :text, :input_html => { :cols => 50, :rows => 3 } %>
          </div>
          <div class="span5">
            <%= f.input :city, :label =>(t "lead.city") %>
            <%= f.input :state, :label =>(t "lead.state") %>
            <%= f.input :zip, :label =>(t "lead.zip") %>
          </div>
        </div>
      </div>
    </div>
    <div class="field-set-container">
      <h1 class="title">Other Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :annual_revenue, :label =>(t "lead.annual_revenue") %>
            <%= f.input :employee_no, :label =>(t "lead.no_of_employee") %>
            <%= f.input :lead_source, :label =>(t "lead.lead_source") %>
          </div>
          <div class="span5">
            <%= f.input :description, :as => :text, :input_html => { :cols => 50, :rows => 3 } %>
          </div>
        </div>
      </div>
    </div>


    <div class="form-actions">
      <div class="btn-group">
        <%= f.submit nil, :class => "btn btn-primary" %>
        <%= link_to t("global.cancel"), leads_path, :class => "btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/leads/show.html.erb
<div class="row-fluid page-title">
  <h2>Lead Details</h2>
</div>

<div class="field-set-container">
  <h1 class="title">Personal Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "lead.title" %></span>
          <span class="field-value">
            <% if @lead.title.nil? || @lead.title == '' %>
              N/A
            <% else %>
              <%= @lead.title %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.first_name" %></span>
          <span class="field-value">
            <% if @lead.firstname.nil? || @lead.firstname == '' %>
              N/A
            <% else %>
              <%= @lead.firstname %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.last_name" %></span>
          <span class="field-value">
            <%= @lead.lastname %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.email" %></span>
          <span class="field-value">
            <%= @lead.email %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "lead.status" %></span>
          <span class="field-value">
            <% if @lead.status == 1 %>
              Active
            <% else %>
              Inactive
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.company" %></span>
          <span class="field-value">
            <% if @lead.company.nil? || @lead.company == '' %>
              N/A
            <% else %>
              <%= @lead.company %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.phone" %></span>
          <span class="field-value">
            <% if @lead.phone.nil? || @lead.phone == '' %>
              N/A
            <% else %>
              <%= @lead.phone %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.ratting" %></span>
          <span class="field-value">
            <% if @lead.ratting.nil? || @lead.ratting == '' %>
              N/A
            <% else %>
              <%= @lead.company %>
            <% end %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="field-set-container">
  <h1 class="title">Address Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "lead.address" %></span>
          <span class="field-value">
            <% if !@lead.street.nil?  %>
              <%= @lead.street %>
            <% end %>
            <% if !@lead.city.nil? %>
              <%= @lead.city %>
            <% end %>
            <% if !@lead.state.nil? %>
              <%= @lead.state %>
            <% end %>
            <% if !@lead.zip.nil? %>
              <%= @lead.zip %>
            <% end %>
            <% if (@lead.street.nil? || @lead.street == '') && (@lead.city.nil? || @lead.city == '') && (@lead.state.nil? || @lead.state == '') && (@lead.zip.nil? || @lead.zip == '')  %>
              N/A
            <% end %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="field-set-container">
  <h1 class="title">Other Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "lead.annual_revenue" %></span>
          <span class="field-value">
            <% if @lead.annual_revenue.nil? || @lead.annual_revenue == '' %>
              N/A
            <% else %>
              <%= @lead.annual_revenue %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.employee_no" %></span>
          <span class="field-value">
            <% if @lead.employee_no.nil? || @lead.employee_no == '' %>
              N/A
            <% else %>
              <%= @lead.employee_no %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "lead.lead_source" %></span>
          <span class="field-value">
            <% if @lead.lead_source.nil? || @lead.lead_source == '' %>
              N/A
            <% else %>
              <%= @lead.lead_source %>
            <% end %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "lead.description" %></span>
          <span class="field-value">
            <% if @lead.description.nil? || @lead.description == '' %>
              N/A
            <% else %>
              <%= @lead.description %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.created_at" %></span>
          <span class="field-value">
            <%= @lead.created_at.to_formatted_s(:db) %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.updated_at" %></span>
          <span class="field-value">
            <%= @lead.updated_at.to_formatted_s(:db) %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="form-actions" style="text-align: center;">
  <div class="btn-group">
    <a class="btn btn-small" href="<%= edit_lead_path(:id => @lead.unique_id) %>">Edit</a>
    <%= link_to "Delete", lead_path(:id => @lead.unique_id),:confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %>
    <a class="btn btn-small" href="<%= leads_path %>">Cancel</a>
  </div>
</div>
<div class="clear"></div>