config/routes.rb
Community::Application.routes.draw do
  devise_for :members,:controllers => { :registrations =>'registration'}
  devise_for :members ,:controllers => {:passwords => "passwords"} do
    resources :passwords
  end

  match 'dashboard' => 'home#dashboard'

  match 'register' =>'registration#register'
  
  root :to => 'home#index'

  resources :contacts
  resources :accounts
  resources :contracts
  resources :opportunity
  resources :users
  resources :roles

  resources :leads do
    collection do
      put :convert_lead
    end
  end
  match 'lead/:id/convert' => 'leads#convert_lead', :as => :convert_lead
  match 'leads/:id' => 'leads#update', :via => [:post]
  match 'contacts/:id' => 'contacts#update', :via => [:post]
  match 'accounts/:id' => 'accounts#update', :via => [:post]
  match 'account/:id/get_contacts' => 'accounts#get_contacts', :as => :get_contacts, :via => [:get]
  match 'users/:id/edit' => 'users#update', :via => [:post]
  match 'passwords/:id/edit' => 'passwords#update', :via => [:post]
  match 'users/new' => 'users#create', :via => [:post]
  match 'roles/:id/edit' => 'roles#update', :via => [:post]
  match 'roles/new' => 'roles#create', :via => [:post]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :member, :foreign_key => "owner"
  belongs_to :account, :foreign_key => "account_name"
  # Mass Assignment Protection
  attr_accessible :firstname, :lastname, :title, :status, :phone, :email, :account_name, :position,
                  :m_street, :m_city, :m_state, :m_zip, :m_country,
                  :o_street, :o_city, :o_state, :o_zip, :o_country,:owner, :unique_id

  # Validations for Contacts
  validates_presence_of :lastname, :email
  validates_format_of  :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :email
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user

  def index
    @contacts = Contact.find(:all)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @accounts = Account.find(:all, :conditions => [ "status = ?", 1 ])
    @contact = Contact.new
    if !params[:accid].nil?
      @find = Account.where("unique_id = ?", params[:accid]).first
      if !@find.nil?
        @contact.account_name =@find.id
      end
    end
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact[:owner] =  current_member.id
    @contact[:unique_id] = genarate_unique_key
    respond_to do |format|
      begin
        if @contact.save
          format.json { render :json => {"success" => true, "message" => "Successfully created!"} }
        else
          format.json { render :json => {"error" => true, "exception" => @contact.errors.full_messages.to_sentence} }
        end
      rescue =>e
        @error= e.message
        format.json { render :json => {"error" => true, "exception" => @error} }
      end
    end
  end

  def show
    @title = t "contact.t_view"
    @contact = Contact.find_by_unique_id(params[:id])
  end

  def edit
    @title = t "contact.t_edit_contact"
    @accounts = Account.find(:all, :conditions => [ "status = ?", 1 ])
    @contact = Contact.find_by_unique_id(params[:id])
  end

  def update
    @title = t "contact.t_update_contact"
    @contact = Contact.find_by_unique_id(params[:id])
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        flash[:notice] = "Successfully updated the contact!"
        format.html { redirect_to(:action => "show") }
        format.xml { head :ok }
      else
        flash[:error] = @contact.errors.full_messages.to_sentence
        format.html { redirect_to :action => "edit" }
      end
    end
  end

  def destroy
    @title = t "contact.t_delete_contactt"
    @contact = Contact.find_by_unique_id(params[:id])
    @contact.destroy
    respond_to do |format|
      flash[:notice] = "Contact deleted successfully!"
      format.html { redirect_to(contacts_path) }
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact_list.html.erb
<div class="row-fluid">
  <div class="span12">
    <%if @contacts.count <= 0 %>
      <div class="alert alert-notice">There is no contacts found!</div>
    <%  else %>
      <table class="table table-bordered table-hover table table-condensed">
        <thead>
          <tr>
            <th><%= (t "contact.title") %></th>
            <th><%= (t "contact.first_name") %></th>
            <th><%= (t "contact.last_name") %></th>
            <th><%= (t "contact.email") %></th>
            <th><%= (t "contact.account_name") %></th>
            <th><%= (t "contact.phone") %></th>
            <th colspan="2"><%= (t "contact.status") %></th>
          </tr>
        </thead>
        <tbody>
          <% for contact in @contacts do %>
              <tr class="<%= cycle :odd, :even %>">
                <td style="text-transform:capitalize;">
                  <% if contact.title.nil? || contact.title == '' %>
                    N/A
                  <% else %>
                    <%= contact.title %>
                  <% end %>
                </td>
                <td>
                  <% if contact.firstname.nil? || contact.firstname == '' %>
                    N/A
                  <% else %>
                    <%= contact.firstname %>
                  <% end %>
                </td>
                <td><%= contact.lastname %></td>
                <td><%= contact.email %></td>
                <td style="text-transform:capitalize;">
                  <% if contact.account_name.nil? || contact.account_name == '' %>
                    N/A
                  <%  else %>
                    <%= link_to contact.account.account_name, account_path(:id => contact.account.unique_id) %>
                  <% end %>
                </td>
                <td>
                  <% if contact.phone.nil? || contact.phone == '' %>
                    N/A
                  <% else %>
                    <%= contact.phone %>
                  <% end %>
                </td>
                <td style="text-transform:capitalize;">
                  <% if contact.status == 1 %>
                    Active
                  <% else %>
                    Inactive
                  <% end %>
                </td>
                <td>
                  <div class="btn-group">
                    <a class="btn btn-small" href="<%= contact_path(:id => contact.unique_id) %>">Details</a>
                    <a class="btn btn-small" href="<%= edit_contact_path(:id => contact.unique_id) %>">Edit</a>
                    <%= link_to "Delete", contact_path(:id => contact.unique_id),:confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <%  end %>
    </div>
  </div>

app/views/contacts/edit.html.erb
<div class="row-fluid page-title">
  <h2>Update Contact</h2>
</div>
<div id="editContact">
  <div id="ajaxHandler">
    <div class="row-fluid">
      <div id="crmAjaxProgress" class="progress progress-striped active" style="display: none;">
        <div class="bar" style="width: 100%;"></div>
      </div>
      <div id="crmAjaxMessage" class="alert" style="display: none;">
        Error!
      </div>
    </div>
  </div>
  <%= simple_form_for(@contact, :url => contact_path(:id => @contact.unique_id), :method => :update, :html => {:class => "form-horizontal"})  do |f| %>
    <div class="field-set-container">
      <h1 class="title">Personal Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :title, :collection =>[["Mr.","Mr."],["Mrs.","Mrs."]], :selected => "Mr." %>
            <%= f.input :firstname, :label => (t "contact.first_name") %>
            <%= f.input :lastname, :label => (t "contact.last_name") %>
            <%= f.input :email, :label =>(t "contact.email") %>
          </div>
          <div class="span5">
            <%= f.input :phone, :label =>(t "contact.phone") %>
            <%= f.association :account, collection: @accounts.map{ |account| [account.account_name, account.id]}, :include_blank => "Select Account", :selected => @contact.account_name %>
            <%= f.input :position, :label =>(t "contact.position") %>
            <%= f.input :status, :collection =>[["Active","1"],["Inactive","2"]], :selected => @contact.status %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Address Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :m_street, :as => :text, :label => (t "contact.mailing_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :m_city, :label =>(t "contact.mailing_city") %>
            <%= f.input :m_state, :label =>(t "contact.mailing_state") %>
            <%= f.input :m_zip, :label =>(t "contact.mailing_zip") %>
          </div>
          <div class="span5">
            <%= f.input :o_street, :as => :text, :label => (t "contact.other_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :o_city, :label =>(t "contact.other_city") %>
            <%= f.input :o_state, :label =>(t "contact.other_state") %>
            <%= f.input :o_zip, :label =>(t "contact.other_zip") %>
          </div>
        </div>
      </div>
    </div>


    <div class="form-actions">
      <div class="btn-group">
        <%= f.submit nil, :class => "btn btn-primary" %>
      <a class="btn btn-small" href="<%= contacts_path(:id => @contact.unique_id) %>">Cancel</a>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/index.html.erb
<div class="row-fluid page-title">
  <h2>Contacts <span class="aside-title-link">[<%= link_to "create", new_contact_path %>]</span></h2>
</div>

<%= render :partial => 'contacts/contact_list' %>

app/views/contacts/new.html.erb
<script>
  form = '', widget = '';
  $.fn.doCreateContact = function(){
    form = $(this);
    widget = $('#createContact');
    $(".alert, .progress, #new_contact", widget).hide();
    $(".progress", widget).show();
    $.post('../contacts', form.serialize(), function(data){
      $(".alert, .progress", widget).hide();
      if(data.success){
        $(".alert", widget)
        .removeClass('alert-error')
        .addClass('alert-success')
        .html(data.message)
        .show();
        setTimeout("window.location.href = '/contacts'",1000);
      } else {
        var $ul = $('<ul/>');
        $ul.addClass('error');
        if (data.exception.indexOf('{') == 0) {
          e = jQuery.parseJSON(data.exception);
          jQuery.each(e, function(key, value) {
            $ul.append('<li>' + value.toString() + '</li>');
          });
        } else {
          $ul.append('<li>' + data.exception + '</li>');
        }
        $(".progress", widget).hide();
        $(".alert", widget)
        .removeClass('alert-success')
        .addClass('alert-error')
        .html($ul)
        .show();
        $("#new_contact", widget).show();
      }

    }).fail(function() {
      $(".progress", widget).hide();
      $(".alert", widget)
      .removeClass('alert-success')
      .addClass('alert-error')
      .html("Error while processing the request!")
      .show();
      $("#new_contact", widget).show();
    });
  }



  $(document).ready(function(){
    $("#new_contact").validate({
      submitHandler: function(form) {
        $(form).doCreateContact();
        return false;
      }
    });
  });
</script>

<div class="row-fluid page-title">
  <h2>Create Contact</h2>
</div>
<div id="createContact">
  <div id="ajaxHandler">
    <div class="row-fluid">
      <div id="crmAjaxProgress" class="progress progress-striped active" style="display: none;">
        <div class="bar" style="width: 100%;"></div>
      </div>
      <div id="crmAjaxMessage" class="alert" style="display: none;">
        Error!
      </div>
    </div>
  </div>
  <%= simple_form_for @contact, :html => {:class => "form-horizontal", :onsubmit => "return false;"}  do |f| %>
    <div class="field-set-container">
      <h1 class="title">Personal Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :title, :collection =>[["Mr.","Mr."],["Mrs.","Mrs."]], :selected => "Mr." %>
            <%= f.input :firstname, :label => (t "contact.first_name") %>
            <%= f.input :lastname, :label => (t "contact.last_name") %>
            <%= f.input :email, :label =>(t "contact.email") %>
          </div>
          <div class="span5">
            <%= f.input :phone, :label =>(t "contact.phone") %>
            <%= f.association :account, collection: @accounts.map{ |account| [account.account_name, account.id]}, :include_blank => "Select Account", :selected => @contact.account_name %>
            <%= f.input :position, :label =>(t "contact.position") %>
            <%= f.input :status, :collection =>[["Active","1"],["Inactive","2"]], :selected => "1" %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Address Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :m_street, :as => :text, :label => (t "contact.mailing_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :m_city, :label =>(t "contact.mailing_city") %>
            <%= f.input :m_state, :label =>(t "contact.mailing_state") %>
            <%= f.input :m_zip, :label =>(t "contact.mailing_zip") %>
          </div>
          <div class="span5">
            <%= f.input :o_street, :as => :text, :label => (t "contact.other_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :o_city, :label =>(t "contact.other_city") %>
            <%= f.input :o_state, :label =>(t "contact.other_state") %>
            <%= f.input :o_zip, :label =>(t "contact.other_zip") %>
          </div>
        </div>
      </div>
    </div>


    <div class="form-actions">
      <div class="btn-group">
        <%= f.submit nil, :class => "btn btn-primary" %>
        <a class="btn btn-small" href="<%= contacts_path %>">Cancel</a>
      </div>
    </div>
  <% end %>
</div>

app/views/contacts/show.html.erb
<div class="row-fluid page-title">
  <h2>Contact Details</h2>
</div>

<div class="field-set-container">
  <h1 class="title">Personal Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "contact.title" %></span>
          <span class="field-value">
            <% if @contact.title.nil? || @contact.title == '' %>
              N/A
            <% else %>
              <%= @contact.title %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.first_name" %></span>
          <span class="field-value">
            <% if @contact.firstname.nil? || @contact.firstname == '' %>
              N/A
            <% else %>
              <%= @contact.firstname %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.last_name" %></span>
          <span class="field-value">
            <%= @contact.lastname %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.email" %></span>
          <span class="field-value">
            <%= @contact.email %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "contact.phone" %></span>
          <span class="field-value">
            <% if @contact.phone.nil? || @contact.phone == '' %>
              N/A
            <% else %>
              <%= @contact.phone %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.account_name" %></span>
          <span class="field-value">
            <% if @contact.account_name.nil? || @contact.account_name == '' %>
              N/A
            <% else %>
              <%= link_to @contact.account.account_name, account_path(:id => @contact.account.unique_id) %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.position" %></span>
          <span class="field-value">
            <% if @contact.position.nil? || @contact.position == '' %>
              N/A
            <% else %>
              <%= @contact.position %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "contact.status" %></span>
          <span class="field-value">
            <% if @contact.status == 1 %>
              Active
            <% else %>
              Inactive
            <% end %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="field-set-container">
  <h1 class="title">Address Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "contact.mailing_address" %></span>
          <span class="field-value">
            <% if !@contact.m_street.nil?  %>
              <%= @contact.m_street %>
            <% end %>
            <% if !@contact.m_city.nil? %>
              <%= @contact.m_city %>
            <% end %>
            <% if !@contact.m_state.nil? %>
              <%= @contact.m_state %>
            <% end %>
            <% if !@contact.m_zip.nil? %>
              <%= @contact.m_zip %>
            <% end %>
            <% if (@contact.m_street.nil? || @contact.m_street == '') && (@contact.m_city.nil? || @contact.m_city == '') && (@contact.m_state.nil? || @contact.m_state == '') && (@contact.m_zip.nil? || @contact.m_zip == '')  %>
              N/A
            <% end %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "contact.other_street" %></span>
          <span class="field-value">
            <% if !@contact.o_street.nil? %>
              <%= @contact.o_street %>
            <% end %>
            <% if !@contact.o_city.nil? %>
              <%= @contact.o_city %>
            <% end %>
            <% if !@contact.o_state.nil? %>
              <%= @contact.o_state %>
            <% end %>
            <% if !@contact.o_zip.nil? %>
              <%= @contact.o_zip %>
            <% end %>
            <% if (@contact.o_street.nil? || @contact.o_street == '') && (@contact.o_city.nil? || @contact.o_city == '') && (@contact.o_state.nil? || @contact.o_state == '') && (@contact.o_zip.nil? || @contact.o_zip == '')  %>
              N/A
            <% end %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="field-set-container">
  <h1 class="title">Other Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "contact.created_at" %></span>
          <span class="field-value">
            <%= @contact.created_at.to_formatted_s(:db) %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "contact.updated_at" %></span>
          <span class="field-value">
            <%= @contact.updated_at.to_formatted_s(:db) %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="form-actions" style="text-align: center;">
  <div class="btn-group">
    <a class="btn btn-small" href="<%= edit_contact_path(:id => @contact.unique_id) %>">Edit</a>
    <%= link_to "Delete", contact_path(:id => @contact.unique_id),:confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %>
    <a class="btn btn-small" href="<%= contacts_path %>">Cancel</a>
  </div>
</div>
<div class="clear"></div>