config/routes.rb
Community::Application.routes.draw do
  devise_for :members,:controllers => { :registrations =>'registration'}
  devise_for :members ,:controllers => {:passwords => "passwords"} do
    resources :passwords
  end

  match 'dashboard' => 'home#dashboard'

  match 'register' =>'registration#register'
  
  root :to => 'home#index'

  resources :contacts
  resources :accounts
  resources :contracts
  resources :opportunity
  resources :users
  resources :roles

  resources :leads do
    collection do
      put :convert_lead
    end
  end
  match 'lead/:id/convert' => 'leads#convert_lead', :as => :convert_lead
  match 'leads/:id' => 'leads#update', :via => [:post]
  match 'contacts/:id' => 'contacts#update', :via => [:post]
  match 'accounts/:id' => 'accounts#update', :via => [:post]
  match 'account/:id/get_contacts' => 'accounts#get_contacts', :as => :get_contacts, :via => [:get]
  match 'users/:id/edit' => 'users#update', :via => [:post]
  match 'passwords/:id/edit' => 'passwords#update', :via => [:post]
  match 'users/new' => 'users#create', :via => [:post]
  match 'roles/:id/edit' => 'roles#update', :via => [:post]
  match 'roles/new' => 'roles#create', :via => [:post]

end

app/views/layouts/_navbar.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li class="<%= 'active' if(controller.controller_name == "home") %>"><%= link_to "Home", root_path %></li>
        <% if current_member %>

          <li class="<%= 'active' if(controller.controller_name == "leads") %>"><%= link_to "Leads", leads_path %></li>
          <li class="<%= 'active' if(controller.controller_name == "contacts") %>"><%= link_to "Contacts", contacts_path %></li>
          <li class="<%= 'active' if(controller.controller_name == "accounts") %>"><%= link_to "Accounts", accounts_path %></li>

          <% if current_member.role_id != 3 %>
            <li class="<%= 'active' if(controller.controller_name == "opportunity") %>"><%= link_to "Opportunities", opportunity_index_path %></li>
            <li class="<%= 'active' if(controller.controller_name == "contracts") %>"><%= link_to "Contracts", contracts_path %></li>
          <% end %>

          <li id="settingsmenu" class="dropdown <%= 'active' if(controller.controller_name == "users" || controller.controller_name == "passwords" || controller.controller_name == "roles") %>">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Settings<b class="caret"></b></a>
            <ul class="dropdown-menu pull-right">
              <li class="<%= 'active' if current_page?(edit_user_path(:id => current_member.unique_id)) %>"><a href="<%= edit_user_path(:id => current_member.unique_id) %>">Edit Profile</a></li>
              <li class="<%= 'active' if current_page?(edit_password_path(:id => current_member.unique_id)) %>"><a href="<%= edit_password_path(:id => current_member.unique_id) %>">Change Password</a></li>
              <li class="divider"></li>

              <% if current_member.role_id == 1 %>
                <li class="<%= 'active' if current_page?(new_user_path) %>"><%= link_to "Create User", new_user_path %></li>
                <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Manage Users", users_path %></li>
                <li class="<%= 'active' if current_page?(roles_path) %>"><%= link_to "Manage Roles", roles_path %></li>
                <li class="divider"></li>
              <% end %>

              <li><%= link_to "Sign Out", destroy_member_session_path, :method=>:delete %></li>
            </ul>
          </li>

        <% else %>
          <li class="<%= 'active' if(controller.controller_name != "registration" && controller.controller_name != "users" && controller.controller_name != "home" ) %>"><%= link_to "Sign In", new_member_session_path(current_member) %></li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evolvinx CRM Demo</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        <%= render 'layouts/header' %>
        <%= render 'layouts/navbar' %>
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <%= msg %>
          </div>
        <% end %>
        <div id="contentPlaceHolder">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>