config/routes.rb
Community::Application.routes.draw do
  devise_for :members,:controllers => { :registrations =>'registration'}
  devise_for :members ,:controllers => {:passwords => "passwords"} do
    resources :passwords
  end

  match 'dashboard' => 'home#dashboard'

  match 'register' =>'registration#register'
  
  root :to => 'home#index'

  resources :contacts
  resources :accounts
  resources :contracts
  resources :opportunity
  resources :users
  resources :roles

  resources :leads do
    collection do
      put :convert_lead
    end
  end
  match 'lead/:id/convert' => 'leads#convert_lead', :as => :convert_lead
  match 'leads/:id' => 'leads#update', :via => [:post]
  match 'contacts/:id' => 'contacts#update', :via => [:post]
  match 'accounts/:id' => 'accounts#update', :via => [:post]
  match 'account/:id/get_contacts' => 'accounts#get_contacts', :as => :get_contacts, :via => [:get]
  match 'users/:id/edit' => 'users#update', :via => [:post]
  match 'passwords/:id/edit' => 'passwords#update', :via => [:post]
  match 'users/new' => 'users#create', :via => [:post]
  match 'roles/:id/edit' => 'roles#update', :via => [:post]
  match 'roles/new' => 'roles#create', :via => [:post]

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :contact, :dependent => :delete_all, :foreign_key => 'account_name'
  belongs_to :member, :foreign_key => "owner"
  # Mass Assignment Protection
  attr_accessible :account_name, :status, :phone, :fax, :website, :discount, :type, :industry, :employees, :annual_revenue, :description,
                  :b_street, :b_city, :b_state, :b_zip, :b_country,
                  :s_street, :s_city, :s_state, :s_zip, :s_country, :owner,:unique_id

  # Validations for Users
  validates_presence_of :account_name
  validates_uniqueness_of :account_name
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user

  def index
    @accounts = Account.find(:all)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(params[:account])
    @account[:owner] =  current_member.id
    @account[:unique_id] =  genarate_unique_key
    respond_to do |format|
      begin
        if @account.save
          format.json { render :json => {"success" => true, "message" => "Successfully created!"} }
        else
          format.json { render :json => {"error" => true, "exception" => @account.errors.full_messages.to_sentence} }
        end
      rescue =>e
        @error= e.message
        format.json { render :json => {"error" => true, "exception" => @error} }
      end
    end
  end

  def show
    @title = t "account.t_view"
    @account = Account.find_by_unique_id(params[:id])
  end

  def edit
    @title = t "account.t_edit_account"
    @account = Account.find_by_unique_id(params[:id])
  end

  def update
    @title = t "account.t_update_account"
    @account = Account.find_by_unique_id(params[:id])
    respond_to do |format|
      if @account.update_attributes(params[:account])
        flash[:notice] = "Successfully updated the account!"
        format.html { redirect_to(:action => "show") }
        format.xml { head :ok }
      else
        flash[:error] = @account.errors.full_messages.to_sentence
        format.html { redirect_to :action => "edit" }
      end
    end
  end

  def get_contacts
    @accKey = params[:id]
    @find = Account.where("unique_id = ?", @accKey).first
    @contacts = Contact.find(:all, :conditions => [ "account_name = ?", @find.id ])
    render :layout => false
  end

  def destroy
    @title = t "account.t_delete_account"
    @account = Account.find_by_unique_id(params[:id])
    @account.destroy
    respond_to do |format|
      flash[:notice] = "Account deleted successfully!"
      format.html { redirect_to(accounts_path) }
    end
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account_list.html.erb
<div class="row-fluid">
  <div class="span12">
    <%if @accounts.count <= 0 %>
    <div class="alert alert-notice">There is no accounts found!</div>
    <%  else %>
    <table class="table table-bordered table-hover table table-condensed">
      <thead>
        <tr>
          <th><%= (t "account.account_name") %></th>
          <th><%= (t "account.type") %></th>
          <th><%= (t "account.industry") %></th>
          <th><%= (t "account.employees") %></th>
          <th><%= (t "account.annual_revenue") %></th>
          <th colspan="2"><%= (t "account.status") %></th>
        </tr>
      </thead>
      <tbody>
        <% for account in @accounts do %>
            <tr class="<%= cycle :odd, :even %>">
              <td style="text-transform:capitalize;"><%= account.account_name %></td>
              <td style="text-transform:capitalize;">
                <% if account.type.nil? || account.type == '' %>
                  N/A
                <% else %>
                  <%= account.type %>
                <% end %>
              </td>
              <td style="text-transform:capitalize;">
                <% if account.industry.nil? || account.industry == ''  %>
                  N/A
                <% else %>
                  <%= account.industry %>
                <% end %>
              </td>
              <td>
                <% if account.employees.nil? || account.employees == '' %>
                  N/A
                <% else %>
                  <%= account.employees %>
                <% end %>
              </td>
              <td>
                <% if account.annual_revenue.nil? || account.annual_revenue == '' %>
                  N/A
                <% else %>
                  <%= account.annual_revenue %>
                <% end %>
              </td>
              <td style="text-transform:capitalize;">
                <% if account.status == 1 %>
                  Active
                <% else %>
                  Inactive
                <% end %>
              </td>
              <td>
                <div class="btn-group">
                  <a class="btn btn-small" href="<%= account_path(:id => account.unique_id) %>">Details</a>
                  <a class="btn btn-small" href="<%= edit_account_path(:id => account.unique_id) %>">Edit</a>
                  <a id="<%= account.unique_id %>" class="btn btn-small lnk-contact" href="javascript://">Contacts</a>
                  <%= link_to "Delete", account_path(:id => account.unique_id),:confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%  end %>
    </div>
  </div>



  <div id="alertModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="alertModalLabel" aria-hidden="true" data-backdrop="true" style="width: 80%;left: 9%; margin-left: auto;">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3 id="alertModalLabel" class="nts-modal-title"></h3>
    </div>
    <div class="modal-body">
      <p id="alertContent"></p>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
    </div>
  </div>

app/views/accounts/edit.html.erb
<div class="row-fluid page-title">
  <h2>Update Account</h2>
</div>
<div id="editAccount">
  <div id="ajaxHandler">
    <div class="row-fluid">
      <div id="crmAjaxProgress" class="progress progress-striped active" style="display: none;">
        <div class="bar" style="width: 100%;"></div>
      </div>
      <div id="crmAjaxMessage" class="alert" style="display: none;">
        Error!
      </div>
    </div>
  </div>
  <%= simple_form_for(@account, :url => account_path(:id => @account.unique_id), :method => :update, :html => {:class => "form-horizontal"})  do |f| %>
    <div class="field-set-container">
      <h1 class="title">Basic Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :account_name, :label => (t "account.account_name") %>
            <%= f.input :phone, :label =>(t "account.phone") %>
            <%= f.input :fax, :label =>(t "account.fax") %>
            <%= f.input :website, :label =>(t "account.website") %>
          </div>
          <div class="span5">
            <%= f.input :status, :collection =>[["Select",""],["Active","1"],["Inactive","2"]], :selected => @account.status %>
            <%= f.input :type, :label =>(t "account.type") %>
            <%= f.input :discount, :label =>(t "account.client_discount") %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Address Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :b_street, :as => :text, :label => (t "account.business_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :b_city, :label =>(t "account.business_city") %>
            <%= f.input :b_state, :label =>(t "account.business_state") %>
            <%= f.input :b_zip, :label =>(t "account.business_zip") %>
          </div>
          <div class="span5">
            <%= f.input :s_street, :as => :text, :label => (t "account.shipping_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :s_city, :label =>(t "account.shipping_city") %>
            <%= f.input :s_state, :label =>(t "account.shipping_state") %>
            <%= f.input :s_zip, :label =>(t "account.shipping_zip") %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Other Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :industry, :label =>(t "account.industry") %>
            <%= f.input :employees, :label =>(t "account.employees") %>
            <%= f.input :annual_revenue, :label =>(t "account.annual_revenue") %>
          </div>
          <div class="span5">
            <%= f.input :description, :as => :text, :input_html => { :cols => 50, :rows => 4 } %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <div class="btn-group">
        <%= f.submit nil, :class => "btn btn-primary" %>
        <input type="button" class="btn" onclick="window.location='<%= account_path(:id => @account.unique_id) %>'" value="Cancel" />
      </div>
    </div>
  <% end %>
</div>

app/views/accounts/get_contacts.html.erb
<div class="row-fluid">
  <div class="span12">
    <p style="text-align: right;">
      <%= link_to "Create New", {:controller => "contacts", :action => "new", :accid => params[:id]}, {:class => 'btn'} %>
    </p>

    <%if @contacts.count <= 0 %>
    <div class="alert alert-notice">There is no contacts for this account!</div>
    <%  else %>
      <table class="table table-bordered table-hover table table-condensed">
        <thead>
          <tr>
            <th><%= (t "contact.title") %></th>
            <th><%= (t "contact.first_name") %></th>
            <th><%= (t "contact.last_name") %></th>
            <th><%= (t "contact.email") %></th>
            <th><%= (t "contact.account_name") %></th>
            <th><%= (t "contact.phone") %></th>
            <th colspan="2"><%= (t "contact.status") %></th>
          </tr>
        </thead>
        <tbody>
          <% for contact in @contacts do %>
              <tr class="<%= cycle :odd, :even %>">
                <td style="text-transform:capitalize;">
                  <% if contact.title.nil? || contact.title == '' %>
                    N/A
                  <% else %>
                    <%= contact.title.strip %>
                  <% end %>
                </td>
                <td>
                  <% if contact.firstname.nil? || contact.firstname == '' %>
                    N/A
                  <% else %>
                    <%= contact.firstname %>
                  <% end %>
                </td>
                <td><%= contact.lastname %></td>
                <td><%= contact.email %></td>
                <td style="text-transform:capitalize;">
                  <% if contact.account_name.nil? || contact.account_name == '' %>
                    N/A
                  <%  else %>
                    <%= contact.account.account_name %>
                  <% end %>
                </td>
                <td>
                  <% if contact.phone.nil? || contact.phone == '' %>
                    N/A
                  <% else %>
                    <%= contact.phone %>
                  <% end %>
                </td>
                <td style="text-transform:capitalize;">
                  <% if contact.status == 1 %>
                    Active
                  <% else %>
                    Inactive
                  <% end %>
                </td>
                <td>
                  <div class="btn-group">
                    <a class="btn btn-small" href="<%= contact_path(:id => contact.unique_id) %>">Details</a>
                    <a class="btn btn-small" href="<%= edit_contact_path(:id => contact.unique_id) %>">Edit</a>
                    <%= link_to "Delete", contact_path(:id => contact.unique_id),:confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <%  end %>
    </div>
  </div>

app/views/accounts/index.html.erb
<div class="row-fluid page-title">
  <h2>Accounts <span class="aside-title-link">[<%= link_to "create", new_account_path %>]</span></h2>
</div>

<%= render :partial => 'accounts/account_list' %>

<script>
  $(".lnk-contact").bind('click', function(e){
    var _id = $(this).attr("id");
    $('#alertContent').html("");
    $('#alertModalLabel').html('Contacts');
    $('#alertModal').modal('show');
    $('#alertContent').html("Loading ...");
    $.ajax({
      url: '../account/'+_id+'/get_contacts',
      success: function(html){
        $('#alertContent').html(html);
      }
    });
    return false;
  });
</script>

app/views/accounts/new.html.erb
<script>

  form = '', widget = '';
  $.fn.doCreateAccount = function(){
    form = $(this);
    widget = $('#createAccount');
    $(".alert, .progress, #new_account", widget).hide();
    $(".progress", widget).show();
    $.post('../accounts', form.serialize(), function(data){
      $(".alert, .progress", widget).hide();
      if(data.success){
        $(".alert", widget)
        .removeClass('alert-error')
        .addClass('alert-success')
        .html(data.message)
        .show();
        setTimeout("window.location.href = '/accounts'",1000);
      } else {
        var $ul = $('<ul/>');
        $ul.addClass('error');
        if (data.exception.indexOf('{') == 0) {
          e = jQuery.parseJSON(data.exception);
          jQuery.each(e, function(key, value) {
            $ul.append('<li>' + value.toString() + '</li>');
          });
        } else {
          $ul.append('<li>' + data.exception + '</li>');
        }
        $(".progress", widget).hide();
        $(".alert", widget)
        .removeClass('alert-success')
        .addClass('alert-error')
        .html($ul)
        .show();
        $("#new_account", widget).show();
      }

    }).fail(function() {
      $(".progress", widget).hide();
      $(".alert", widget)
      .removeClass('alert-success')
      .addClass('alert-error')
      .html("Error while processing the request!")
      .show();
      $("#new_account", widget).show();
    });
  }



  $(document).ready(function(){
    $("#new_account").validate({
      submitHandler: function(form) {
        $(form).doCreateAccount();
        return false;
      }
    });
  });

</script>
<div class="row-fluid page-title">
  <h2>Create Account</h2>
</div>
<div id="createAccount">
  <div id="ajaxHandler">
    <div class="row-fluid">
      <div id="crmAjaxProgress" class="progress progress-striped active" style="display: none;">
        <div class="bar" style="width: 100%;"></div>
      </div>
      <div id="crmAjaxMessage" class="alert" style="display: none;">
        Error!
      </div>
    </div>
  </div>
  <%= simple_form_for @account, :html => {:class => "form-horizontal", :onsubmit => "return false;"}  do |f| %>
    <div class="field-set-container">
      <h1 class="title">Basic Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :account_name, :label => (t "account.account_name") %>
            <%= f.input :phone, :label =>(t "account.phone") %>
            <%= f.input :fax, :label =>(t "account.fax") %>
            <%= f.input :website, :label =>(t "account.website") %>
          </div>
          <div class="span5">
            <%= f.input :status, :collection =>[["Active","1"],["Inactive","2"]], :selected => "1" %>
            <%= f.input :type, :label =>(t "account.type") %>
            <%= f.input :discount, :label =>(t "account.client_discount") %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Address Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :b_street, :as => :text, :label => (t "account.business_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :b_city, :label =>(t "account.business_city") %>
            <%= f.input :b_state, :label =>(t "account.business_state") %>
            <%= f.input :b_zip, :label =>(t "account.business_zip") %>
          </div>
          <div class="span5">
            <%= f.input :s_street, :as => :text, :label => (t "account.shipping_street"), :input_html => { :cols => 50, :rows => 3 } %>
            <%= f.input :s_city, :label =>(t "account.shipping_city") %>
            <%= f.input :s_state, :label =>(t "account.shipping_state") %>
            <%= f.input :s_zip, :label =>(t "account.shipping_zip") %>
          </div>
        </div>
      </div>
    </div>

    <div class="field-set-container">
      <h1 class="title">Other Information</h1>
      <div class="body">
        <div class="row-fluid">
          <div class="span5">
            <%= f.input :industry, :label =>(t "account.industry") %>
            <%= f.input :employees, :label =>(t "account.employees") %>
            <%= f.input :annual_revenue, :label =>(t "account.annual_revenue") %>
          </div>
          <div class="span5">
            <%= f.input :description, :as => :text, :input_html => { :cols => 50, :rows => 3 } %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-actions">
      <div class="btn-group">
        <%= f.submit nil, :class => "btn btn-primary" %>
        <a class="btn btn-small" href="<%= accounts_path %>">Cancel</a>
      </div>
    </div>
  <% end %>
</div>

app/views/accounts/show.html.erb
<div class="row-fluid page-title">
  <h2>Account Details</h2>
</div>

<div class="field-set-container">
  <h1 class="title">Basic Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "account.account_name" %></span>
          <span class="field-value"><%= @account.account_name %></span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.phone" %></span>
          <span class="field-value">
            <% if @account.phone.nil? || @account.phone == '' %>
              N/A
            <% else %>
              <%= @account.phone %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.fax" %></span>
          <span class="field-value">
            <% if @account.fax.nil? || @account.fax == '' %>
              N/A
            <% else %>
              <%= @account.fax %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.website" %></span>
          <span class="field-value">
            <% if @account.website.nil? || @account.website == '' %>
              N/A
            <% else %>
              <%= @account.website %>
            <% end %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "account.status" %></span>
          <span class="field-value">
            <% if @account.status == 1 %>
              Active
            <% else %>
              Inactive
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.type" %></span>
          <span class="field-value">
            <% if @account.type.nil? || @account.type == '' %>
              N/A
            <% else %>
              <%= @account.type %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.client_discount" %></span>
          <span class="field-value">
            <% if @account.discount.nil? || @account.discount == '' %>
              N/A
            <% else %>
              <%= @account.discount %>
            <% end %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="field-set-container">
  <h1 class="title">Address Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "account.business_address" %></span>
          <span class="field-value">
            <% if !@account.b_street.nil?  %>
              <%= @account.b_street %>
            <% end %>
            <% if !@account.b_city.nil? %>
              <%= @account.b_city %>
            <% end %>
            <% if !@account.b_state.nil? %>
              <%= @account.b_state %>
            <% end %>
            <% if !@account.b_zip.nil? %>
              <%= @account.b_zip %>
            <% end %>
            <% if (@account.b_street.nil? || @account.b_street == '') && (@account.b_city.nil? || @account.b_city == '') && (@account.b_state.nil? || @account.b_state == '') && (@account.b_zip.nil? || @account.b_zip == '')  %>
              N/A
            <% end %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "account.shipping_address" %></span>
          <span class="field-value">
            <% if !@account.s_street.nil? %>
              <%= @account.s_street %>
            <% end %>
            <% if !@account.s_city.nil? %>
              <%= @account.s_city %>
            <% end %>
            <% if !@account.s_state.nil? %>
              <%= @account.s_state %>
            <% end %>
            <% if !@account.s_zip.nil? %>
              <%= @account.s_zip %>
            <% end %>
            <% if (@account.s_street.nil? || @account.s_street == '') && (@account.s_city.nil? || @account.s_city == '') && (@account.s_state.nil? || @account.s_state == '') && (@account.s_zip.nil? || @account.s_zip == '')  %>
              N/A
            <% end %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="field-set-container">
  <h1 class="title">Other Information</h1>
  <div class="body">
    <div class="row-fluid">
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "account.industry" %></span>
          <span class="field-value">
            <% if @account.industry.nil? || @account.industry == '' %>
              N/A
            <% else %>
              <%= @account.industry %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.employees" %></span>
          <span class="field-value">
            <% if @account.employees.nil? || @account.employees == '' %>
              N/A
            <% else %>
              <%= @account.employees %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.annual_revenue" %></span>
          <span class="field-value">
            <% if @account.annual_revenue.nil? || @account.annual_revenue == '' %>
              N/A
            <% else %>
              <%= @account.annual_revenue %>
            <% end %>
          </span>
        </p>
      </div>
      <div class="span5">
        <p class="field-row">
          <span class="field-label"><%= t "account.description" %></span>
          <span class="field-value">
            <% if @account.description.nil? || @account.description == '' %>
              N/A
            <% else %>
              <%= @account.description %>
            <% end %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.created_at" %></span>
          <span class="field-value">
            <%= @account.created_at.to_formatted_s(:db) %>
          </span>
        </p>
        <p class="field-row">
          <span class="field-label"><%= t "account.updated_at" %></span>
          <span class="field-value">
            <%= @account.updated_at.to_formatted_s(:db) %>
          </span>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="form-actions" style="text-align: center;">
  <div class="btn-group">
    <a class="btn btn-small" href="<%= edit_account_path(:id => @account.unique_id) %>">Edit</a>
    <%= link_to "Delete", account_path(:id => @account.unique_id),:confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %>
    <a id="<%= @account.unique_id %>" class="btn btn-small lnk-contact" href="javascript://">Contacts</a>
    <a class="btn btn-small" href="<%= accounts_path %>">Cancel</a>
  </div>
</div>
<div class="clear"></div>


<script>
  $(".lnk-contact").bind('click', function(e){
    var _id = $(this).attr("id");
    $('#alertContent').html("");
    $('#alertModalLabel').html('Contacts');
    $('#alertModal').modal('show');
    $('#alertContent').html("Loading ...");
    $.ajax({
      url: '../account/'+_id+'/get_contacts',
      success: function(html){
        $('#alertContent').html(html);
      }
    });
    return false;
  });
</script>

<div id="alertModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="alertModalLabel" aria-hidden="true" data-backdrop="true" style="width: 80%;left: 9%; margin-left: auto;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="alertModalLabel" class="nts-modal-title"></h3>
  </div>
  <div class="modal-body">
    <p id="alertContent"></p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
  </div>
</div>